POST https://banao-test-app.herokuapp.com/register
Content-Type: application/json

{
   "username" : "darshana2",
   "email" : "darshana2@gmail.com",
   "password": "1234" 
}

###
POST https://banao-test-app.herokuapp.com/login
Content-Type: application/json

{
   "username" : "darshana2",
   "password": "1234" 
}

###
POST https://banao-test-app.herokuapp.com/forgetPassword
Content-Type: application/json

{
   "username" : "darshana2",
   "email" : "darshana2@gmail.com",
   "newPass": "4321" 
}

###
GET https://banao-test-app.herokuapp.com/post 

###
POST https://banao-test-app.herokuapp.com/post/create
Content-Type: application/json

{
   "postContent" : "This is a new post"
}

###
PATCH https://banao-test-app.herokuapp.com/post/61c820f20280de21978a374c
Content-Type: application/json

{
   "updatedContent" : "Updated post"
}

###
DELETE https://banao-test-app.herokuapp.com/post/61c820f20280de21978a374c

###
PATCH https://banao-test-app.herokuapp.com/post/like/61c820f20280de21978a374c

###
PATCH https://banao-test-app.herokuapp.com/post/comment/61c820f20280de21978a374c
Content-Type: application/json

{
   "comment" : "Great Post"
}


